=== dqvid3/web-systems-design-architecture-project/gestione/src/main/resources/static/palinsesti/palinsesto.dtd
<!ELEMENT palinsesto (cartellone+)>
        <!ELEMENT cartellone (percorso, folder, durata)>
        <!ELEMENT percorso (#PCDATA)>
        <!ELEMENT folder (#PCDATA)>
        <!ELEMENT durata (#PCDATA)>

=== dqvid3/web-systems-design-architecture-project/gestione/src/main/resources/static/palinsesti/palinsesto4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Decommenta per usare dtd
<!DOCTYPE palinsesto SYSTEM "palinsesto.dtd">
<palinsesto>-->
<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <cartellone>
        <percorso>cartelloni/lidl/lidl.html</percorso>
        <folder>lidl</folder>
        <durata>10</durata>
    </cartellone>
    <cartellone>
        <percorso>cartelloni/omega/omega.html</percorso>
        <folder>omega</folder>
        <durata>10</durata>
    </cartellone>
    <cartellone>
        <percorso>cartelloni/arcteryx/arcteryx.html</percorso>
        <folder>arcteryx</folder>
        <durata>10</durata>
    </cartellone>
</palinsesto>

=== dqvid3/web-systems-design-architecture-project/gestione/target/classes/static/palinsesti/palinsesto3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Decommenta per usare dtd
<!DOCTYPE palinsesto SYSTEM "palinsesto.dtd">
<palinsesto>-->
<palinsesto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="palinsesto.xsd">
    <cartellone>
        <percorso>../cartelloni/phone2a/phone2a.html</percorso>
        <folder>phone2a</folder>
        <durata>10</durata>
    </cartellone>
    <cartellone>
        <percorso>../cartelloni/tesla/tesla.html</percorso>
        <folder>tesla</folder>
        <durata>10</durata>
    </cartellone>
    <cartellone>
        <percorso>../cartelloni/guinness/guinness.html</percorso>
        <folder>guinness</folder>
        <durata>10</durata>
    </cartellone>
    <cartellone>
        <percorso>../cartelloni/pizza/pizza.html</percorso>
        <folder>pizza</folder>
        <durata>10</durata>
    </cartellone>
</palinsesto>
